export interface VehicleModel {
  id: string;
  make: string;
  model: string;
  bodyType: string;
  engineCC: string;
  cylinders: string;
  fuelType: "PETROL" | "DIESEL" | "ELECTRIC";
  netWeight: string;
  grossWeight: string;
  tyreW: string;
  tyreDia: string;
  defaultEnginePrefix?: string;
  popular?: boolean;
  aliases?: string[];
}

export const YEARS_LIST = [
  "2026", "2025", "2024", "2023", "2022", "2021",
  "2020", "2019", "2018", "2017", "2016", "2015",
  "2014", "2013", "2012", "2011", "2010", "2009", "2008"
];

export const VEHICLE_CATALOG: VehicleModel[] = [
  // ── Toyota (Most Common in Ghana) ──
  {
    id: "toyota-corolla",
    make: "Toyota",
    model: "Corolla",
    bodyType: "Saloon",
    engineCC: "1800",
    cylinders: "4",
    fuelType: "PETROL",
    netWeight: "1350",
    grossWeight: "1790",
    tyreW: "205",
    tyreDia: "16",
    defaultEnginePrefix: "2ZR-FE",
    popular: true,
    aliases: ["corolla", "toyota corolla", "sedan"],
  },
  {
    id: "toyota-camry",
    make: "Toyota",
    model: "Camry",
    bodyType: "Saloon",
    engineCC: "2500",
    cylinders: "4",
    fuelType: "PETROL",
    netWeight: "1590",
    grossWeight: "2095",
    tyreW: "215",
    tyreDia: "17",
    defaultEnginePrefix: "2AR-FE",
    popular: true,
    aliases: ["camry", "toyota camry"],
  },
  {
    id: "toyota-hilux",
    make: "Toyota",
    model: "Hilux",
    bodyType: "Pickup / Truck",
    engineCC: "2400",
    cylinders: "4",
    fuelType: "DIESEL",
    netWeight: "1950",
    grossWeight: "3200",
    tyreW: "265",
    tyreDia: "17",
    defaultEnginePrefix: "2GD-FTV",
    popular: true,
    aliases: ["hilux", "toyota pickup", "double cabin"],
  },
  {
    id: "toyota-rav4",
    make: "Toyota",
    model: "RAV4",
    bodyType: "SUV / Station Wagon",
    engineCC: "2500",
    cylinders: "4",
    fuelType: "PETROL",
    netWeight: "1610",
    grossWeight: "2130",
    tyreW: "225",
    tyreDia: "17",
    defaultEnginePrefix: "A25A-FKS",
    popular: true,
    aliases: ["rav4", "rav 4", "toyota rav4"],
  },
  {
    id: "toyota-landcruiser-prado",
    make: "Toyota",
    model: "Land Cruiser Prado",
    bodyType: "SUV / Station Wagon",
    engineCC: "2700",
    cylinders: "4",
    fuelType: "PETROL",
    netWeight: "2150",
    grossWeight: "2990",
    tyreW: "265",
    tyreDia: "17",
    defaultEnginePrefix: "2TR-FE",
    popular: true,
    aliases: ["prado", "land cruiser prado", "tx", "tz"],
  },
  {
    id: "toyota-landcruiser-v8",
    make: "Toyota",
    model: "Land Cruiser V8 / 300",
    bodyType: "SUV / Station Wagon",
    engineCC: "3500",
    cylinders: "6",
    fuelType: "PETROL",
    netWeight: "2630",
    grossWeight: "3350",
    tyreW: "285",
    tyreDia: "18",
    defaultEnginePrefix: "V35A-FTS",
    popular: true,
    aliases: ["land cruiser", "v8", "lc300", "lc200", "cruiser"],
  },
  {
    id: "toyota-highlander",
    make: "Toyota",
    model: "Highlander",
    bodyType: "SUV / Station Wagon",
    engineCC: "2400",
    cylinders: "4",
    fuelType: "PETROL",
    netWeight: "1950",
    grossWeight: "2650",
    tyreW: "235",
    tyreDia: "18",
    defaultEnginePrefix: "T24A-FTS",
    popular: true,
    aliases: ["highlander", "kluger"],
  },
  {
    id: "toyota-yaris",
    make: "Toyota",
    model: "Yaris",
    bodyType: "Hatchback",
    engineCC: "1500",
    cylinders: "4",
    fuelType: "PETROL",
    netWeight: "1100",
    grossWeight: "1550",
    tyreW: "185",
    tyreDia: "15",
    defaultEnginePrefix: "1NZ-FE",
    popular: true,
    aliases: ["yaris", "vitz", "toyota yaris"],
  },
  {
    id: "toyota-fortuner",
    make: "Toyota",
    model: "Fortuner",
    bodyType: "SUV / Station Wagon",
    engineCC: "2800",
    cylinders: "4",
    fuelType: "DIESEL",
    netWeight: "1960",
    grossWeight: "2650",
    tyreW: "265",
    tyreDia: "17",
    defaultEnginePrefix: "1GD-FTV",
    popular: false,
    aliases: ["fortuner"],
  },
  {
    id: "toyota-tacoma",
    make: "Toyota",
    model: "Tacoma",
    bodyType: "Pickup / Truck",
    engineCC: "2400",
    cylinders: "4",
    fuelType: "PETROL",
    netWeight: "1980",
    grossWeight: "2650",
    tyreW: "265",
    tyreDia: "17",
    defaultEnginePrefix: "T24A-FTS",
    popular: false,
    aliases: ["tacoma"],
  },
  {
    id: "toyota-hiace",
    make: "Toyota",
    model: "HiAce",
    bodyType: "Minibus / Van",
    engineCC: "3000",
    cylinders: "4",
    fuelType: "DIESEL",
    netWeight: "2050",
    grossWeight: "3300",
    tyreW: "195",
    tyreDia: "15",
    defaultEnginePrefix: "1KD-FTV",
    popular: false,
    aliases: ["hiace", "van", "trotro", "minibus"],
  },
  {
    id: "toyota-sienna",
    make: "Toyota",
    model: "Sienna",
    bodyType: "Minibus / Van",
    engineCC: "2500",
    cylinders: "4",
    fuelType: "PETROL",
    netWeight: "2100",
    grossWeight: "2750",
    tyreW: "235",
    tyreDia: "17",
    defaultEnginePrefix: "A25A-FXS",
    popular: false,
    aliases: ["sienna", "minivan"],
  },

  // ── Hyundai ──
  {
    id: "hyundai-elantra",
    make: "Hyundai",
    model: "Elantra",
    bodyType: "Saloon",
    engineCC: "1600",
    cylinders: "4",
    fuelType: "PETROL",
    netWeight: "1300",
    grossWeight: "1750",
    tyreW: "205",
    tyreDia: "16",
    defaultEnginePrefix: "G4FG",
    popular: true,
    aliases: ["elantra", "avante"],
  },
  {
    id: "hyundai-tucson",
    make: "Hyundai",
    model: "Tucson",
    bodyType: "SUV / Station Wagon",
    engineCC: "2000",
    cylinders: "4",
    fuelType: "PETROL",
    netWeight: "1680",
    grossWeight: "2145",
    tyreW: "225",
    tyreDia: "17",
    defaultEnginePrefix: "G4NA",
    popular: true,
    aliases: ["tucson", "hyundai tucson"],
  },
  {
    id: "hyundai-sonata",
    make: "Hyundai",
    model: "Sonata",
    bodyType: "Saloon",
    engineCC: "2000",
    cylinders: "4",
    fuelType: "PETROL",
    netWeight: "1490",
    grossWeight: "1980",
    tyreW: "215",
    tyreDia: "17",
    defaultEnginePrefix: "G4KD",
    popular: false,
    aliases: ["sonata"],
  },
  {
    id: "hyundai-santafe",
    make: "Hyundai",
    model: "Santa Fe",
    bodyType: "SUV / Station Wagon",
    engineCC: "2500",
    cylinders: "4",
    fuelType: "PETROL",
    netWeight: "1830",
    grossWeight: "2510",
    tyreW: "235",
    tyreDia: "18",
    defaultEnginePrefix: "G4KN",
    popular: false,
    aliases: ["santa fe", "santafe"],
  },
  {
    id: "hyundai-accent",
    make: "Hyundai",
    model: "Accent",
    bodyType: "Saloon",
    engineCC: "1400",
    cylinders: "4",
    fuelType: "PETROL",
    netWeight: "1180",
    grossWeight: "1600",
    tyreW: "185",
    tyreDia: "15",
    defaultEnginePrefix: "G4LC",
    popular: false,
    aliases: ["accent", "solaris"],
  },
  {
    id: "hyundai-creta",
    make: "Hyundai",
    model: "Creta",
    bodyType: "SUV / Station Wagon",
    engineCC: "1500",
    cylinders: "4",
    fuelType: "PETROL",
    netWeight: "1280",
    grossWeight: "1720",
    tyreW: "205",
    tyreDia: "16",
    defaultEnginePrefix: "G4FL",
    popular: false,
    aliases: ["creta"],
  },

  // ── Honda ──
  {
    id: "honda-civic",
    make: "Honda",
    model: "Civic",
    bodyType: "Saloon",
    engineCC: "1500",
    cylinders: "4",
    fuelType: "PETROL",
    netWeight: "1340",
    grossWeight: "1760",
    tyreW: "215",
    tyreDia: "16",
    defaultEnginePrefix: "L15B7",
    popular: true,
    aliases: ["civic", "honda civic"],
  },
  {
    id: "honda-crv",
    make: "Honda",
    model: "CR-V",
    bodyType: "SUV / Station Wagon",
    engineCC: "1500",
    cylinders: "4",
    fuelType: "PETROL",
    netWeight: "1630",
    grossWeight: "2150",
    tyreW: "235",
    tyreDia: "18",
    defaultEnginePrefix: "L15BE",
    popular: true,
    aliases: ["cr-v", "crv", "honda crv"],
  },
  {
    id: "honda-accord",
    make: "Honda",
    model: "Accord",
    bodyType: "Saloon",
    engineCC: "1500",
    cylinders: "4",
    fuelType: "PETROL",
    netWeight: "1480",
    grossWeight: "1920",
    tyreW: "225",
    tyreDia: "17",
    defaultEnginePrefix: "L15BN",
    popular: true,
    aliases: ["accord", "honda accord"],
  },
  {
    id: "honda-hrv",
    make: "Honda",
    model: "HR-V",
    bodyType: "SUV / Station Wagon",
    engineCC: "1800",
    cylinders: "4",
    fuelType: "PETROL",
    netWeight: "1380",
    grossWeight: "1850",
    tyreW: "215",
    tyreDia: "17",
    defaultEnginePrefix: "R18Z9",
    popular: false,
    aliases: ["hr-v", "hrv"],
  },
  {
    id: "honda-fit",
    make: "Honda",
    model: "Fit / Jazz",
    bodyType: "Hatchback",
    engineCC: "1500",
    cylinders: "4",
    fuelType: "PETROL",
    netWeight: "1100",
    grossWeight: "1520",
    tyreW: "185",
    tyreDia: "15",
    defaultEnginePrefix: "L15Z",
    popular: false,
    aliases: ["fit", "jazz"],
  },

  // ── Mercedes-Benz ──
  {
    id: "mercedes-c-class",
    make: "Mercedes-Benz",
    model: "C-Class (C300 / C200)",
    bodyType: "Saloon",
    engineCC: "2000",
    cylinders: "4",
    fuelType: "PETROL",
    netWeight: "1650",
    grossWeight: "2180",
    tyreW: "225",
    tyreDia: "18",
    defaultEnginePrefix: "M274",
    popular: true,
    aliases: ["c-class", "c300", "c250", "c200", "c180", "benz c class", "mercedes c"],
  },
  {
    id: "mercedes-e-class",
    make: "Mercedes-Benz",
    model: "E-Class (E350 / E200)",
    bodyType: "Saloon",
    engineCC: "2000",
    cylinders: "4",
    fuelType: "PETROL",
    netWeight: "1750",
    grossWeight: "2300",
    tyreW: "245",
    tyreDia: "18",
    defaultEnginePrefix: "M264",
    popular: true,
    aliases: ["e-class", "e350", "e200", "e300", "benz e class", "mercedes e"],
  },
  {
    id: "mercedes-gle",
    make: "Mercedes-Benz",
    model: "GLE (GLE 350 / 450)",
    bodyType: "SUV / Station Wagon",
    engineCC: "2000",
    cylinders: "4",
    fuelType: "PETROL",
    netWeight: "2150",
    grossWeight: "2930",
    tyreW: "265",
    tyreDia: "19",
    defaultEnginePrefix: "M264",
    popular: true,
    aliases: ["gle", "gle 350", "gle 450", "mercedes gle", "ml 350"],
  },
  {
    id: "mercedes-glc",
    make: "Mercedes-Benz",
    model: "GLC (GLC 300)",
    bodyType: "SUV / Station Wagon",
    engineCC: "2000",
    cylinders: "4",
    fuelType: "PETROL",
    netWeight: "1850",
    grossWeight: "2450",
    tyreW: "235",
    tyreDia: "18",
    defaultEnginePrefix: "M264",
    popular: false,
    aliases: ["glc", "glc 300"],
  },
  {
    id: "mercedes-g-wagon",
    make: "Mercedes-Benz",
    model: "G-Class (G63 AMG)",
    bodyType: "SUV / Station Wagon",
    engineCC: "4000",
    cylinders: "8",
    fuelType: "PETROL",
    netWeight: "2560",
    grossWeight: "3200",
    tyreW: "275",
    tyreDia: "20",
    defaultEnginePrefix: "M177",
    popular: false,
    aliases: ["g wagon", "g-class", "g63", "amg"],
  },
  {
    id: "mercedes-sprinter",
    make: "Mercedes-Benz",
    model: "Sprinter",
    bodyType: "Minibus / Van",
    engineCC: "2200",
    cylinders: "4",
    fuelType: "DIESEL",
    netWeight: "2350",
    grossWeight: "3500",
    tyreW: "235",
    tyreDia: "16",
    defaultEnginePrefix: "OM651",
    popular: false,
    aliases: ["sprinter", "benz bus"],
  },

  // ── Kia ──
  {
    id: "kia-sportage",
    make: "Kia",
    model: "Sportage",
    bodyType: "SUV / Station Wagon",
    engineCC: "2000",
    cylinders: "4",
    fuelType: "PETROL",
    netWeight: "1610",
    grossWeight: "2090",
    tyreW: "225",
    tyreDia: "17",
    defaultEnginePrefix: "G4NA",
    popular: true,
    aliases: ["sportage", "kia sportage"],
  },
  {
    id: "kia-forte",
    make: "Kia",
    model: "Forte / Cerato",
    bodyType: "Saloon",
    engineCC: "1600",
    cylinders: "4",
    fuelType: "PETROL",
    netWeight: "1290",
    grossWeight: "1750",
    tyreW: "205",
    tyreDia: "16",
    defaultEnginePrefix: "G4FG",
    popular: false,
    aliases: ["forte", "cerato"],
  },
  {
    id: "kia-sorento",
    make: "Kia",
    model: "Sorento",
    bodyType: "SUV / Station Wagon",
    engineCC: "2500",
    cylinders: "4",
    fuelType: "PETROL",
    netWeight: "1880",
    grossWeight: "2550",
    tyreW: "235",
    tyreDia: "17",
    defaultEnginePrefix: "G4KN",
    popular: false,
    aliases: ["sorento"],
  },
  {
    id: "kia-picanto",
    make: "Kia",
    model: "Picanto",
    bodyType: "Hatchback",
    engineCC: "1200",
    cylinders: "4",
    fuelType: "PETROL",
    netWeight: "980",
    grossWeight: "1400",
    tyreW: "175",
    tyreDia: "14",
    defaultEnginePrefix: "G4LA",
    popular: true,
    aliases: ["picanto", "kia picanto"],
  },

  // ── Lexus ──
  {
    id: "lexus-rx350",
    make: "Lexus",
    model: "RX 350",
    bodyType: "SUV / Station Wagon",
    engineCC: "2400",
    cylinders: "4",
    fuelType: "PETROL",
    netWeight: "1950",
    grossWeight: "2600",
    tyreW: "235",
    tyreDia: "19",
    defaultEnginePrefix: "T24A-FTS",
    popular: true,
    aliases: ["rx 350", "rx350", "lexus rx"],
  },
  {
    id: "lexus-es350",
    make: "Lexus",
    model: "ES 350",
    bodyType: "Saloon",
    engineCC: "3500",
    cylinders: "6",
    fuelType: "PETROL",
    netWeight: "1680",
    grossWeight: "2150",
    tyreW: "215",
    tyreDia: "17",
    defaultEnginePrefix: "2GR-FKS",
    popular: false,
    aliases: ["es 350", "es350", "lexus es"],
  },
  {
    id: "lexus-gx460",
    make: "Lexus",
    model: "GX 460",
    bodyType: "SUV / Station Wagon",
    engineCC: "4600",
    cylinders: "8",
    fuelType: "PETROL",
    netWeight: "2350",
    grossWeight: "2990",
    tyreW: "265",
    tyreDia: "18",
    defaultEnginePrefix: "1UR-FE",
    popular: false,
    aliases: ["gx 460", "gx460", "lexus gx"],
  },

  // ── Nissan ──
  {
    id: "nissan-navara",
    make: "Nissan",
    model: "Navara",
    bodyType: "Pickup / Truck",
    engineCC: "2500",
    cylinders: "4",
    fuelType: "DIESEL",
    netWeight: "1960",
    grossWeight: "3010",
    tyreW: "255",
    tyreDia: "17",
    defaultEnginePrefix: "YD25DDTi",
    popular: true,
    aliases: ["navara", "frontier", "nissan pickup"],
  },
  {
    id: "nissan-rogue",
    make: "Nissan",
    model: "Rogue / X-Trail",
    bodyType: "SUV / Station Wagon",
    engineCC: "2500",
    cylinders: "4",
    fuelType: "PETROL",
    netWeight: "1620",
    grossWeight: "2100",
    tyreW: "225",
    tyreDia: "17",
    defaultEnginePrefix: "QR25DE",
    popular: true,
    aliases: ["rogue", "x-trail", "xtrail"],
  },
  {
    id: "nissan-sentra",
    make: "Nissan",
    model: "Sentra",
    bodyType: "Saloon",
    engineCC: "1800",
    cylinders: "4",
    fuelType: "PETROL",
    netWeight: "1320",
    grossWeight: "1780",
    tyreW: "205",
    tyreDia: "16",
    defaultEnginePrefix: "MRA8DE",
    popular: false,
    aliases: ["sentra", "sunny"],
  },
  {
    id: "nissan-patrol",
    make: "Nissan",
    model: "Patrol",
    bodyType: "SUV / Station Wagon",
    engineCC: "4000",
    cylinders: "6",
    fuelType: "PETROL",
    netWeight: "2650",
    grossWeight: "3400",
    tyreW: "275",
    tyreDia: "18",
    defaultEnginePrefix: "VQ40DE",
    popular: false,
    aliases: ["patrol", "safari"],
  },

  // ── Ford ──
  {
    id: "ford-explorer",
    make: "Ford",
    model: "Explorer",
    bodyType: "SUV / Station Wagon",
    engineCC: "2300",
    cylinders: "4",
    fuelType: "PETROL",
    netWeight: "1970",
    grossWeight: "2790",
    tyreW: "255",
    tyreDia: "18",
    defaultEnginePrefix: "EcoBoost-2.3",
    popular: true,
    aliases: ["explorer", "ford explorer"],
  },
  {
    id: "ford-ranger",
    make: "Ford",
    model: "Ranger",
    bodyType: "Pickup / Truck",
    engineCC: "2000",
    cylinders: "4",
    fuelType: "DIESEL",
    netWeight: "1950",
    grossWeight: "3200",
    tyreW: "265",
    tyreDia: "17",
    defaultEnginePrefix: "Panther-2.0",
    popular: true,
    aliases: ["ranger", "ford ranger"],
  },
  {
    id: "ford-f150",
    make: "Ford",
    model: "F-150",
    bodyType: "Pickup / Truck",
    engineCC: "3500",
    cylinders: "6",
    fuelType: "PETROL",
    netWeight: "2250",
    grossWeight: "3150",
    tyreW: "275",
    tyreDia: "18",
    defaultEnginePrefix: "EcoBoost-3.5",
    popular: false,
    aliases: ["f-150", "f150"],
  },

  // ── BMW ──
  {
    id: "bmw-3series",
    make: "BMW",
    model: "3 Series (320i / 330i)",
    bodyType: "Saloon",
    engineCC: "2000",
    cylinders: "4",
    fuelType: "PETROL",
    netWeight: "1620",
    grossWeight: "2100",
    tyreW: "225",
    tyreDia: "18",
    defaultEnginePrefix: "B48B20",
    popular: false,
    aliases: ["3 series", "320i", "330i", "bmw 3"],
  },
  {
    id: "bmw-x5",
    make: "BMW",
    model: "X5",
    bodyType: "SUV / Station Wagon",
    engineCC: "3000",
    cylinders: "6",
    fuelType: "PETROL",
    netWeight: "2100",
    grossWeight: "2850",
    tyreW: "265",
    tyreDia: "19",
    defaultEnginePrefix: "B58B30",
    popular: false,
    aliases: ["x5", "bmw x5"],
  },

  // ── Jetour & Modern Chinese Models ──
  {
    id: "jetour-dashing",
    make: "Jetour",
    model: "Dashing",
    bodyType: "SUV / Station Wagon",
    engineCC: "1500",
    cylinders: "4",
    fuelType: "PETROL",
    netWeight: "1535",
    grossWeight: "1888",
    tyreW: "235",
    tyreDia: "19",
    defaultEnginePrefix: "SQRE4T15C",
    popular: true,
    aliases: ["dashing", "jetour dashing"],
  },
  {
    id: "jetour-traveller-t2",
    make: "Jetour",
    model: "Traveller T2",
    bodyType: "SUV / Station Wagon",
    engineCC: "2000",
    cylinders: "4",
    fuelType: "PETROL",
    netWeight: "1880",
    grossWeight: "2255",
    tyreW: "255",
    tyreDia: "20",
    defaultEnginePrefix: "SQRF4J20",
    popular: true,
    aliases: ["t2", "traveller", "jetour t2", "traveller t2"],
  },
  {
    id: "byd-atto3",
    make: "BYD",
    model: "Atto 3",
    bodyType: "SUV / Station Wagon",
    engineCC: "N/A (Electric)",
    cylinders: "N/A",
    fuelType: "ELECTRIC",
    netWeight: "1750",
    grossWeight: "2160",
    tyreW: "215",
    tyreDia: "18",
    defaultEnginePrefix: "TZ200XSQ",
    popular: false,
    aliases: ["byd", "atto 3", "electric suv"],
  },

  // ── Land Rover ──
  {
    id: "landrover-rangerover-sport",
    make: "Land Rover",
    model: "Range Rover Sport",
    bodyType: "SUV / Station Wagon",
    engineCC: "3000",
    cylinders: "6",
    fuelType: "PETROL",
    netWeight: "2350",
    grossWeight: "3050",
    tyreW: "275",
    tyreDia: "20",
    defaultEnginePrefix: "AJ300",
    popular: true,
    aliases: ["range rover", "sport", "range rover sport"],
  },
  {
    id: "landrover-defender",
    make: "Land Rover",
    model: "Defender 110",
    bodyType: "SUV / Station Wagon",
    engineCC: "3000",
    cylinders: "6",
    fuelType: "PETROL",
    netWeight: "2380",
    grossWeight: "3150",
    tyreW: "255",
    tyreDia: "19",
    defaultEnginePrefix: "Ingenium-3.0",
    popular: false,
    aliases: ["defender", "defender 110"],
  },

  // ── Mitsubishi ──
  {
    id: "mitsubishi-pajero",
    make: "Mitsubishi",
    model: "Pajero",
    bodyType: "SUV / Station Wagon",
    engineCC: "3200",
    cylinders: "4",
    fuelType: "DIESEL",
    netWeight: "2180",
    grossWeight: "3030",
    tyreW: "265",
    tyreDia: "17",
    defaultEnginePrefix: "4M41",
    popular: false,
    aliases: ["pajero", "montero"],
  },
  {
    id: "mitsubishi-l200",
    make: "Mitsubishi",
    model: "L200 / Triton",
    bodyType: "Pickup / Truck",
    engineCC: "2400",
    cylinders: "4",
    fuelType: "DIESEL",
    netWeight: "1920",
    grossWeight: "2910",
    tyreW: "245",
    tyreDia: "16",
    defaultEnginePrefix: "4N15",
    popular: false,
    aliases: ["l200", "triton"],
  },

  // ── Volkswagen ──
  {
    id: "vw-passat",
    make: "Volkswagen",
    model: "Passat",
    bodyType: "Saloon",
    engineCC: "1800",
    cylinders: "4",
    fuelType: "PETROL",
    netWeight: "1520",
    grossWeight: "2050",
    tyreW: "215",
    tyreDia: "17",
    defaultEnginePrefix: "EA888",
    popular: false,
    aliases: ["passat", "vw passat"],
  },
  {
    id: "vw-tiguan",
    make: "Volkswagen",
    model: "Tiguan",
    bodyType: "SUV / Station Wagon",
    engineCC: "2000",
    cylinders: "4",
    fuelType: "PETROL",
    netWeight: "1680",
    grossWeight: "2220",
    tyreW: "235",
    tyreDia: "18",
    defaultEnginePrefix: "EA888",
    popular: false,
    aliases: ["tiguan", "vw tiguan"],
  },

  // ── Suzuki ──
  {
    id: "suzuki-swift",
    make: "Suzuki",
    model: "Swift",
    bodyType: "Hatchback",
    engineCC: "1200",
    cylinders: "4",
    fuelType: "PETROL",
    netWeight: "920",
    grossWeight: "1360",
    tyreW: "185",
    tyreDia: "15",
    defaultEnginePrefix: "K12M",
    popular: true,
    aliases: ["swift", "suzuki swift"],
  },
  {
    id: "suzuki-vitara",
    make: "Suzuki",
    model: "Vitara",
    bodyType: "SUV / Station Wagon",
    engineCC: "1600",
    cylinders: "4",
    fuelType: "PETROL",
    netWeight: "1180",
    grossWeight: "1730",
    tyreW: "215",
    tyreDia: "17",
    defaultEnginePrefix: "M16A",
    popular: false,
    aliases: ["vitara", "grand vitara"],
  },

  // ── Tesla (Electric) ──
  {
    id: "tesla-model-y",
    make: "Tesla",
    model: "Model Y",
    bodyType: "SUV / Station Wagon",
    engineCC: "N/A (Electric)",
    cylinders: "N/A",
    fuelType: "ELECTRIC",
    netWeight: "1910",
    grossWeight: "2405",
    tyreW: "255",
    tyreDia: "19",
    defaultEnginePrefix: "3D3-DUAL",
    popular: false,
    aliases: ["tesla", "model y", "ev"],
  },
  {
    id: "tesla-model-3",
    make: "Tesla",
    model: "Model 3",
    bodyType: "Saloon",
    engineCC: "N/A (Electric)",
    cylinders: "N/A",
    fuelType: "ELECTRIC",
    netWeight: "1760",
    grossWeight: "2200",
    tyreW: "235",
    tyreDia: "18",
    defaultEnginePrefix: "3D1-MOTOR",
    popular: false,
    aliases: ["model 3", "tesla 3"],
  },
];

/**
 * Filter vehicles by search query (checks make, model, category, and aliases)
 */
export function searchVehicles(query: string): VehicleModel[] {
  if (!query || !query.trim()) return VEHICLE_CATALOG;
  const clean = query.toLowerCase().trim();
  return VEHICLE_CATALOG.filter((v) => {
    if (v.make.toLowerCase().includes(clean)) return true;
    if (v.model.toLowerCase().includes(clean)) return true;
    if (`${v.make} ${v.model}`.toLowerCase().includes(clean)) return true;
    if (v.bodyType.toLowerCase().includes(clean)) return true;
    if (v.aliases?.some((a) => a.includes(clean))) return true;
    return false;
  });
}

/**
 * Generates an appropriate, realistic engine number format for the selected vehicle
 */
export function generateEngineNumber(v: VehicleModel): string {
  if (v.fuelType === "ELECTRIC") {
    const rand = Math.floor(100000 + Math.random() * 900000);
    return `EV-${v.make.slice(0, 2).toUpperCase()}-${rand}`;
  }
  const prefix = v.defaultEnginePrefix || `${v.make.slice(0, 3).toUpperCase()}${v.engineCC.slice(0, 2)}`;
  const serial = Math.floor(100000 + Math.random() * 900000);
  return `${prefix}-${serial}`;
}
